version: "3.1"

services:
  app:
    build: .
    networks:
      - people-counter
    ports:
      - 8789:8000
  redis:
    image: redis
    networks:
      - people-counter
  inferoxy:
    networks:
      - people-counter
    image: public.registry.visionhub.ru/inferoxy:v1.0.4
    env_file:
      - .env.inferoxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./models.yaml:/etc/inferoxy/models.yaml

networks:
  people-counter:
